pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Swetha210506/FAT_LAB_Agile.git'
            }
        }

        stage('Compile') {
            steps {
                bat 'javac auction_system/src/main/java/AuctionService.java'
            }
        }

        stage('Run') {
            steps {
                bat 'java -cp auction_system/src/main/java AuctionService'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t auction-app auction_system'
            }
        }

        stage('Docker Run') {
            steps {
                bat 'docker run auction-app'
            }
        }
    }
}
