pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                git 'https://github.com/Swetha210506/FAT_LAB_Agile.git'
            }
        }

        stage('Maven Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t auction-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run auction-app'
            }
        }
    }
}
